executors:
    base:
        docker:
            - image: cimg/base:2021.04
jobs:
    test:
        executor: base
        parameters:
            package:
                type: string
        steps:
            - checkout
            - bun/install
            - run: bun install
            - run: bun test
        working_directory: ~/project/<< parameters.package >>
    types:
        executor: base
        parameters:
            package:
                type: string
        steps:
            - checkout
            - bun/install
            - run: bun install
            - run: bun types
        working_directory: ~/project/packages/<< parameters.package >>
orbs:
    bun: ksylvest/bun@1.0.1
parameters:
    service-a:
        default: false
        type: boolean
    service-b:
        default: false
        type: boolean
version: 2.1
workflows:
    code-validation:
        jobs:
            - test:
                matrix:
                    parameters:
                        package:
                            - service-a
                            - service-b
            - types:
                matrix:
                    parameters:
                        package:
                            - service-a
                            - service-b

